version: "3"

services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_perqara
      MYSQL_USER: ada
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: pwd
      #MYSQL_ROOT_HOST: "172.21.0.1" # prefer belongs to your network
    volumes:
      - ./infra/migration/perqara.sql:/docker-entrypoint-initdb.d/perqara.sql
      - ./infra/storage/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    restart: always
    hostname: backend
    environment:
      DATABASE_NAME: db_perqara
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: password
      DATABASE_USER: ada
    volumes:
      - ".:/usr/src/app"
      - /usr/src/app/node_modules/
    build: .
    command: npm start
  # deploy:
  #   resources:
  #     limits:
  #         memory: 500M
  #   replicas: 3
